name: CI/CD Pipeline

on:
  push:
    branches:
      - frontend

jobs:
  scan-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install -g @sonarqube-scanner/cli

      - name: Analyze code with SonarQube
        run: sonar-scanner

      - name: Run Trivy on code
        run: |
          docker run --rm \
            -v "$(pwd)/frontend:/app" \
            aquasec/trivy --exit-code 1 --severity HIGH,MEDIUM,LOW /app

  build-and-test-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: frontend

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker buildx create --use && docker buildx build --push -t "$DOCKERHUB_USERNAME"/flaskappfront:latest ./frontend

      - name: Run tests on the Docker image
        run: |
          docker run --rm \
            aquasec/trivy --exit-code 1 --severity HIGH,MEDIUM,LOW "$DOCKERHUB_USERNAME"/flaskappfront:latest > trivy.txt
          # Add your additional test commands here

  push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: frontend

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Push Docker image to Docker Hub
        run: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push "$DOCKERHUB_USERNAME"/flaskappfront:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
